In [5]:
import pandas as pd
import numpy as np
import pylab as plt
from sklearn.cluster import KMeans
from pandas import ExcelWriter
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pyodbc
connection = pyodbc.connect("DRIVER={SQL Server};"
                  "SERVER=2.144.246.200,49790\GALAXYDB;"
                  "DATABASE=Galaxy;"
                  "UID=sa;"
                  "PWD=@Galaxy258#shaygan;"
                  "TrustServerCertificate=no;"
                  "Connection Timeout=60")

cursor=connection.cursor()

In [ ]:
SQLCommand=("select [Date] as [Datetime], [INDEX] as [Index], [CELL_Name] as [eNodeB], [DL_User_Throughput(Mbps)] as [User_Thr_Mbps] from BI.Data_4G where cast([Date] as date)='2020-04-20'")
cursor.execute(SQLCommand)
results=cursor.fetchall()

In [6]:
d=[]
for row in results:
    d.append({'Datetime':row.Datetime, 'eNodeB':row.eNodeB, 'Index':row.Index, 'User_Thr_Mbps':row.User_Thr_Mbps})
LTE_KPI=pd.DataFrame(d)
LTE_KPI

                   Datetime Index  User_Thr_Mbps      eNodeB
0       2020-04-20 03:00:00    GN      12.655000  GN2L0583C1
1       2020-04-20 03:00:00    KJ      23.496000  KJ1L0301B1
2       2020-04-20 03:00:00    KJ      27.215000  KJ1L0745B1
3       2020-04-20 03:00:00    KJ       7.521000  KJ1L0745C1
4       2020-04-20 03:00:00    MA      33.000000  MA1L0125B1
5       2020-04-20 03:00:00    TH      10.055000  TH1L0755C1
6       2020-04-20 03:00:00    TH      12.761000  TH1L1577B2
7       2020-04-20 03:00:00    TH      10.566000  TH1L2123A2
8       2020-04-20 03:00:00    TH      23.230000  TH1L2306B1
9       2020-04-20 03:00:00    TH      14.183000  TH1L2319B1
10      2020-04-20 03:00:00    TH       6.128000  TH2L0372B1
11      2020-04-20 03:00:00    TH      17.285999  TH2L0545C1
12      2020-04-20 03:00:00    TH      10.117000  TH2L0619B1
13      2020-04-20 03:00:00    TH      47.910999  TH2L0841B1
14      2020-04-20 03:00:00    TH      26.816999  TH2L0967B1
15      2020-04-20 03:00:00    TH       8.308000  TH2L1428C1
16      2020-04-20 03:00:00    TH            NaN  TH2L2523C1
17      2020-04-20 05:00:00    GN      44.428001  GN1L0288B1
18      2020-04-20 05:00:00    KJ      30.455000  KJ1L0706B1
19      2020-04-20 05:00:00    MA      79.042999  MA2L0148C1
20      2020-04-20 05:00:00    MA      19.260000  MA2L0524B1
21      2020-04-20 05:00:00    MA      27.648001  MA2L0653A1
22      2020-04-20 05:00:00    TH      14.536000  TH1L1573A1
23      2020-04-20 05:00:00    TH      29.801001  TH1L2096C1
24      2020-04-20 03:00:00    TH      13.355000  TH1L0352A2
25      2020-04-20 03:00:00    TH      11.783000  TH1L0641A1
26      2020-04-20 03:00:00    TH      21.594000  TH1L0786B1
27      2020-04-20 03:00:00    TH       9.578000  TH2L0236B1
28      2020-04-20 03:00:00    TH      29.872000  TH2L0723C1
29      2020-04-20 03:00:00    TH       9.880000  TH2L0853C1
...                     ...   ...            ...         ...
1817816 2020-04-20 23:00:00    TH      16.396000  TH2L1525B1
1817817 2020-04-20 23:00:00    TH       2.734000  TH2L1791B1
1817818 2020-04-20 18:00:00    TH      18.316999  TH2L0858C1
1817819 2020-04-20 19:00:00    GN      19.165001  GN2L0405A1
1817820 2020-04-20 19:00:00    GN      20.468000  GN2L0603B1
1817821 2020-04-20 19:00:00    KJ      21.896000  KJ1L0013A1
1817822 2020-04-20 19:00:00    KJ       3.417000  KJ1L0037A2
1817823 2020-04-20 19:00:00    KJ       9.668000  KJ1L0104B1
1817824 2020-04-20 19:00:00    MA      15.050000  MA1L0012A1
1817825 2020-04-20 16:00:00    MA       7.776000  MA2L0469A1
1817826 2020-04-20 16:00:00    TH      17.076000  TH1L0972C1
1817827 2020-04-20 16:00:00    TH       8.519000  TH1L1010C2
1817828 2020-04-20 16:00:00    TH      14.081000  TH1L1801C1
1817829 2020-04-20 16:00:00    TH       2.996000  TH2L0346B1
1817830 2020-04-20 16:00:00    TH      22.218000  TH2L1854A1
1817831 2020-04-20 16:00:00    TH      22.188000  TH2L2519C1
1817832 2020-04-20 17:00:00    KJ       6.863000  KJ1L0017A1
1817833 2020-04-20 17:00:00    KJ      12.338000  KJ1L0107A2
1817834 2020-04-20 17:00:00    KJ       7.670000  KJ2L0701B1
1817835 2020-04-20 22:00:00    MA      12.705000  MA2L0334B1
1817836 2020-04-20 22:00:00    MA      12.016000  MA2L0406B1
1817837 2020-04-20 22:00:00    MA      24.506001  MA2L0591A1
1817838 2020-04-20 12:00:00    TH      16.268999  TH1L1431B1
1817839 2020-04-20 12:00:00    TH      10.759000  TH1L2041B2
1817840 2020-04-20 12:00:00    TH      19.188000  TH2L0489A1
1817841 2020-04-20 12:00:00    TH      10.189000  TH2L0942A1
1817842 2020-04-20 13:00:00    KJ      24.108999  KJ1L0240C2
1817843 2020-04-20 13:00:00    KJ       8.066000  KJ1L0753A2
1817844 2020-04-20 13:00:00    KJ       7.889000  KJ2L0016B1
1817845 2020-04-20 13:00:00    KJ       6.792000  KJ2L0689C1

[1817846 rows x 4 columns]

In [7]:
SQLCommand2=("select [Date] as [Datetime], [CELLID] as [eNodeB], [Average_Number_of_RRC_Connected_Users] as [Connected_User] from BI.Connected_User_4G where cast([Date] as date)='2020-04-20'")
cursor.execute(SQLCommand2)
results2=cursor.fetchall()

In [8]:
d2=[]
for row in results2:
    d2.append({'Datetime':row.Datetime, 'eNodeB':row.eNodeB, 'Connected_User':row.Connected_User})
Connected=pd.DataFrame(d2)
Connected

         Connected_User            Datetime      eNodeB
0             23.049000 2020-04-20 20:00:00  KJ2L0860A1
1             33.340000 2020-04-20 02:00:00  TH1L0701C1
2             43.976002 2020-04-20 23:00:00  TH1L1728A1
3             38.313000 2020-04-20 12:00:00  TH1L1656A2
4             42.636002 2020-04-20 12:00:00  TH1L2247A2
5              5.551000 2020-04-20 03:00:00  GL1L0204B1
6             22.750999 2020-04-20 20:00:00  GL2L0513A1
7             11.486000 2020-04-20 09:00:00  TH1L1287B1
8             66.818001 2020-04-20 16:00:00  TH1L1336C1
9             18.378000 2020-04-20 09:00:00  TH2L0066C1
10            11.760000 2020-04-20 22:00:00  TH2L0183C1
11            12.449000 2020-04-20 09:00:00  GL2L0269B1
12            42.325001 2020-04-20 08:00:00  KJ1L0108C1
13            28.714001 2020-04-20 06:00:00  TH1L0235C1
14            22.839001 2020-04-20 08:00:00  TH1L0637B1
15            17.434999 2020-04-20 01:00:00  TH1L0961B1
16             2.139000 2020-04-20 01:00:00  TH1L1485B1
17            40.853001 2020-04-20 12:00:00  TH2L0591A1
18            42.139999 2020-04-20 20:00:00  KJ1L0339B1
19             2.117000 2020-04-20 00:00:00  KJ1L0625B2
20            38.195999 2020-04-20 00:00:00  MA1L0631C2
21           137.889999 2020-04-20 00:00:00  TH1L0221C1
22            57.882999 2020-04-20 16:00:00  TH1L1163B1
23             4.504000 2020-04-20 03:00:00  TH1L0621C2
24            52.918999 2020-04-20 22:00:00  TH1L1051C2
25            43.450001 2020-04-20 02:00:00  TH2L0118C1
26            30.834999 2020-04-20 18:00:00  TH2L1369C1
27            49.089001 2020-04-20 01:00:00  TH2L1663A1
28            34.825001 2020-04-20 12:00:00  GN2L0264C1
29            68.653000 2020-04-20 21:00:00  TH1L0796B1
...                 ...                 ...         ...
1814837       17.043000 2020-04-20 04:00:00  FS1L0160A1
1814838       10.388000 2020-04-20 20:00:00  FS2L0188B1
1814839       70.284000 2020-04-20 12:00:00  YZ2L0337C1
1814840       18.418000 2020-04-20 15:00:00  NK1L0202A1
1814841       11.028000 2020-04-20 02:00:00  SK1L0209A2
1814842       42.064000 2020-04-20 11:00:00  KH1L0340C1
1814843        6.607000 2020-04-20 05:00:00  KM2L0620B1
1814844       23.297000 2020-04-20 13:00:00  KM2L0218A1
1814845       20.601000 2020-04-20 09:00:00  KH1L1405C2
1814846       40.969000 2020-04-20 18:00:00  MK1L0378B1
1814847       66.572000 2020-04-20 20:00:00  FS2L0007C1
1814848       51.794000 2020-04-20 13:00:00  YZ2L0377C1
1814849       58.972000 2020-04-20 19:00:00  MK2L0203B1
1814850       71.479000 2020-04-20 18:00:00  YZ1L0256C1
1814851       19.359000 2020-04-20 07:00:00  KM1L0056A1
1814852       48.893000 2020-04-20 09:00:00  KH2L0258A1
1814853       23.059000 2020-04-20 13:00:00  MK1L0388B1
1814854       21.651000 2020-04-20 07:00:00  MK2L0336A1
1814855       26.006000 2020-04-20 02:00:00  KH2L0923B1
1814856        0.000000 2020-04-20 09:00:00  FS2L2511A1
1814857       46.187000 2020-04-20 19:00:00  CH2L0070C1
1814858       32.958000 2020-04-20 13:00:00  KM2L0930B1
1814859       18.029000 2020-04-20 00:00:00  YZ1L0105A2
1814860       34.953000 2020-04-20 01:00:00  FS2L0293C1
1814861        5.199000 2020-04-20 21:00:00  KH2L0362B1
1814862      126.659000 2020-04-20 23:00:00  MK2L0379C1
1814863       28.213000 2020-04-20 22:00:00  SK1L0357C1
1814864       32.109000 2020-04-20 07:00:00  KM2L0508B1
1814865        8.201000 2020-04-20 08:00:00  NK2L0254C1
1814866       33.234000 2020-04-20 01:00:00  SB1L0135A1

[1814867 rows x 3 columns]

# Analysis

In [9]:
data = pd.merge(LTE_KPI,Connected,how='left',on=['Datetime','eNodeB'])

In [15]:
data['Sector'] = data['eNodeB']
data.Sector = data.eNodeB.str.slice(0, 2) + data.eNodeB.str.slice(4, 9)

data_den = data.groupby(['Index','Sector', 'Datetime'])['Connected_User'].agg(sum)

data_mult = pd.DataFrame()
data_mult['UDT'] = data['User_Thr_Mbps'] * data['Connected_User']
data_mult['Datetime'] = data['Datetime']
data_mult['Sector'] = data['Sector']
data_mult['Index'] = data['Index']

data_mult_sum = data_mult.groupby(['Index','Sector', 'Datetime'])['UDT'].agg(sum)

data_merged = pd.concat([ data_mult_sum, data_den], axis = 1, sort=False)
data_merged['User_Thr_Mbps'] = data_merged['UDT'] / (data_merged['Connected_User'] + (data_merged['Connected_User'] == 0))
data_merged.drop(['UDT'], axis=1, inplace = True)
data_merged_df = data_merged.reset_index()

df1argmax = data_merged_df.groupby('Sector', as_index=False).apply(lambda x: x.loc[x.Connected_User.idxmax(),])
df1argmax['Site'] = df1argmax.Sector.str.slice(0, 6)

In [16]:
df1argmax['Status_code'] = np.where(df1argmax['User_Thr_Mbps']<3,0,\
                              np.where(df1argmax['User_Thr_Mbps']<5,1,\
                                       np.where(df1argmax['User_Thr_Mbps']<10,2,3)))

df1argmax['Status_name'] = np.where(df1argmax['User_Thr_Mbps']<3,'Thr < 3 (Mbps)',\
                              np.where(df1argmax['User_Thr_Mbps']<5,'3 (Mbps) < Thr < 5 (Mbps)',\
                                       np.where(df1argmax['User_Thr_Mbps']<10,'5 (Mbps) < Thr < 10 (Mbps)','Thr > 10 (Mbps)')))

In [17]:
Prv_Name = pd.read_excel(r"D:\Shayan THR Report\Report File\New Province.xlsx",sheet_name='Province')
Prv_Name = Prv_Name[['Index','Province_P','Province_E']]
Total_data_sector = pd.merge(df1argmax,Prv_Name,how='left',on=['Index'])
Total_data_sector.to_excel(r'D:\Shayan THR Report\Report File\{}\Sector_Report.xlsx'.format(Date),'Main')

In [18]:
##### Sector Dashboard #####

Total_data_sector_true = Total_data_sector[Total_data_sector['Connected_User']!=0]
Total_data_sector_true = Total_data_sector_true[Total_data_sector_true['User_Thr_Mbps']!=0]

df_Agg = Total_data_sector_true.groupby(['Province_P','Status_name'],as_index=False)['Index'].count()
df_Result = df_Agg.pivot(index='Province_P', columns='Status_name', values='Index')
df_Result = df_Result.reset_index()

sums = df_Result.select_dtypes(pd.np.number).sum().rename('Iran')
df_Result = df_Result.append(sums)
df_Result['Province_P']['Iran'] = 'ایران'

df_Result['# Site'] = df_Result['3 (Mbps) < Thr < 5 (Mbps)']+df_Result['5 (Mbps) < Thr < 10 (Mbps)']+df_Result['Thr < 3 (Mbps)']+df_Result['Thr > 10 (Mbps)']
df_Result['3 (Mbps) < %Thr < 5 (Mbps)'] = 100*df_Result['3 (Mbps) < Thr < 5 (Mbps)']/df_Result['# Site']
df_Result['5 (Mbps) < %Thr < 10 (Mbps)'] = 100*df_Result['5 (Mbps) < Thr < 10 (Mbps)']/df_Result['# Site']
df_Result['%Thr < 3 (Mbps)'] = 100*df_Result['Thr < 3 (Mbps)']/df_Result['# Site']
df_Result['%Thr > 10 (Mbps)'] = 100*df_Result['Thr > 10 (Mbps)']/df_Result['# Site']

df_Result.to_excel(r'D:\Shayan THR Report\Report File\{}\Prv_Result_Sector.xlsx'.format(Date))
df_Result.to_excel(r'D:\Shayan THR Report\Report File\PowerBi\Prv_Result_Sector.xlsx')

In [19]:
Total_data_site = Total_data_sector.groupby('Site', as_index=False).apply(lambda x: x.loc[x.User_Thr_Mbps.idxmin(),])
Total_data_site_true = Total_data_site[Total_data_site['Connected_User']!=0]
Total_data_site_true = Total_data_site_true[Total_data_site_true['User_Thr_Mbps']!=0]

Total_data_site_true.to_excel(r'D:\Shayan THR Report\Report File\{}\Site_Report.xlsx'.format(Date),'Main')

In [20]:
##### Site Dashboard #####

df_Agg = Total_data_site_true.groupby(['Province_P','Status_name'],as_index=False)['Index'].count()
df_Result = df_Agg.pivot(index='Province_P', columns='Status_name', values='Index')
df_Result = df_Result.reset_index()

sums = df_Result.select_dtypes(pd.np.number).sum().rename('Iran')
df_Result = df_Result.append(sums)
df_Result['Province_P']['Iran'] = 'ایران'

df_Result['# Site'] = df_Result['3 (Mbps) < Thr < 5 (Mbps)']+df_Result['5 (Mbps) < Thr < 10 (Mbps)']+df_Result['Thr < 3 (Mbps)']+df_Result['Thr > 10 (Mbps)']
df_Result['3 (Mbps) < %Thr < 5 (Mbps)'] = 100*df_Result['3 (Mbps) < Thr < 5 (Mbps)']/df_Result['# Site']
df_Result['5 (Mbps) < %Thr < 10 (Mbps)'] = 100*df_Result['5 (Mbps) < Thr < 10 (Mbps)']/df_Result['# Site']
df_Result['%Thr < 3 (Mbps)'] = 100*df_Result['Thr < 3 (Mbps)']/df_Result['# Site']
df_Result['%Thr > 10 (Mbps)'] = 100*df_Result['Thr > 10 (Mbps)']/df_Result['# Site']

df_Result.to_excel(r'D:\Shayan THR Report\Report File\{}\Prv_Result_Site.xlsx'.format(Date))
df_Result.to_excel(r'D:\Shayan THR Report\Report File\PowerBi\Prv_Result_Site.xlsx')

In [21]:
Geography_data = pd.read_excel(r"D:\Shayan THR Report\Report File\Lat&Long-ArasDB.xlsx",sheet_name='Sheet1')
Geography_data = Geography_data[['Site','Lat','Long']]
Total_data_site_Geography = pd.merge(Total_data_site_true,Geography_data,on=['Site'])

In [22]:
site = Total_data_site_Geography
site = site.sort_values(by=['Status_code'])
site = site.reset_index(drop=True)
site = site[['Site','Status_name','Lat','Long']]

df1 = site.iloc[0:2000]
df2 = site.iloc[2000:4000]
df3 = site.iloc[4000:6000]
df4 = site.iloc[6000:8000]
df5 = site.iloc[8000:10000]
df6 = site.iloc[10000:12000]
df7 = site.iloc[12000:len(site['Site'])]

df1.to_excel(r'D:\Shayan THR Report\Report File\{}\df1.xlsx'.format(Date))
df2.to_excel(r'D:\Shayan THR Report\Report File\{}\df2.xlsx'.format(Date))
df3.to_excel(r'D:\Shayan THR Report\Report File\{}\df3.xlsx'.format(Date))
df4.to_excel(r'D:\Shayan THR Report\Report File\{}\df4.xlsx'.format(Date))
df5.to_excel(r'D:\Shayan THR Report\Report File\{}\df5.xlsx'.format(Date))
df6.to_excel(r'D:\Shayan THR Report\Report File\{}\df6.xlsx'.format(Date))
df7.to_excel(r'D:\Shayan THR Report\Report File\{}\df7.xlsx'.format(Date))

# Site Hourly

In [23]:
data['Site'] = data['eNodeB']
data.Site = data.eNodeB.str.slice(0, 2) + data.eNodeB.str.slice(4, 8)

hourly_site_den = data.groupby(['Index','Site','Datetime'])['Connected_User'].agg(sum)

hourly_site_mult = pd.DataFrame()
hourly_site_mult['UDT'] = data['User_Thr_Mbps'] * data['Connected_User']
hourly_site_mult['Datetime'] = data['Datetime']
hourly_site_mult['Site'] = data['Site']
hourly_site_mult['Index'] = data['Index']

hourly_site_mult_sum = hourly_site_mult.groupby(['Index','Site','Datetime'])['UDT'].agg(sum)

hourly_site_merged = pd.concat([ hourly_site_mult_sum, hourly_site_den], axis = 1, sort=False)
hourly_site_merged['User_Thr_Mbps'] = hourly_site_merged['UDT'] / (hourly_site_merged['Connected_User'] + (hourly_site_merged['Connected_User'] == 0))
hourly_site_merged.drop(['UDT'], axis=1, inplace = True)
hourly_site_merged_df = hourly_site_merged.reset_index()

site_Hour_max = hourly_site_merged_df.groupby('Site', as_index=False).apply(lambda x: x.loc[x.Connected_User.idxmax(),])

# Site Daily

In [24]:
daily_site_den = hourly_site_merged_df.groupby(['Index','Site'])['Connected_User'].agg(sum)

daily_site_mult = pd.DataFrame()
daily_site_mult['UDT'] = hourly_site_merged_df['User_Thr_Mbps'] * hourly_site_merged_df['Connected_User']
daily_site_mult['Site'] = hourly_site_merged_df['Site']
daily_site_mult['Index'] = hourly_site_merged_df['Index']

daily_site_mult_sum = daily_site_mult.groupby(['Index','Site'])['UDT'].agg(sum)

daily_site_merged = pd.concat([ daily_site_mult_sum, daily_site_den], axis = 1, sort=False)
daily_site_merged['User_Thr_Mbps'] = daily_site_merged['UDT'] / (daily_site_merged['Connected_User'] + (daily_site_merged['Connected_User'] == 0))
daily_site_merged.drop(['UDT'], axis=1, inplace = True)
daily_site_merged_df = daily_site_merged.reset_index()

# Low Sector

In [25]:
Sector_Hour_max = Total_data_site

# No. Carrir per Sector

In [26]:
data_uniq = data.groupby(['eNodeB'],as_index=False)['Connected_User'].max()
data_uniq['Sector'] = data_uniq.eNodeB.str.slice(0, 2) + data_uniq.eNodeB.str.slice(4, 9)
data_sector_uniq = data_uniq.groupby(['Sector'],as_index=False)['eNodeB'].count()
data_sector_uniq['Site'] = data_sector_uniq.Sector.str.slice(0, 6)
Carrir_per_Sector = data_sector_uniq.groupby(['Site'],as_index=False)['eNodeB'].max()

# Daily Connected User

In [27]:
Site_Connected_Hourly = data.groupby(['Datetime','Site'],as_index=False)['Connected_User'].sum()

In [28]:
Site_Connected_Daily = Site_Connected_Hourly.groupby(['Site'],as_index=False)['Connected_User'].mean()

# Marge Thr

In [29]:
BW = pd.read_excel(r'D:\Shayan THR Report\Report File\{}\Bandwidth.xlsx'.format(Date),sheet_name='Sheet1')

In [30]:
Thr1 = pd.merge(daily_site_merged_df[['Site','User_Thr_Mbps']],site_Hour_max[['Site','User_Thr_Mbps']], on='Site' ,how='left')
Thr2 = pd.merge(Thr1,Sector_Hour_max[['Site','User_Thr_Mbps']], on='Site' ,how='left')
Thr3 = pd.merge(Thr2,Carrir_per_Sector, on='Site' ,how='left')
Thr4 = pd.merge(Thr3,BW, on='Site' ,how='left')
Thr5 = pd.merge(Thr4,Site_Connected_Daily, on='Site' ,how='left')

In [31]:
Merge_Thr = Thr5.rename({'User_Thr_Mbps_x':'Daily User Thr (Mbps)','User_Thr_Mbps_y':'Min Hourly User Thr (Mbps)','User_Thr_Mbps':'Min Hourly Sector User Thr sector(Mbps)','eNodeB':'No. Carrir per Sector','BW_MHz':'Site BW'}, axis='columns')

In [32]:
Merge_Thr.to_excel(r'D:\Shayan THR Report\Report File\{}\Throughput.xlsx'.format(Date))

# Top Traffic Site

In [33]:
HT_Site = pd.read_excel(r'D:\Shayan THR Report\Report File\{}\HighTraffic_Site.xlsx'.format(Date),sheet_name='Sheet1')
HT_Site = HT_Site[['Site','Daily Payload (GB)']]
Site_Address = pd.read_excel(r'D:\Shayan THR Report\Report File\Site-Address.xlsx',sheet_name='Sheet1')

HT_Site_Thr1 = pd.merge(HT_Site,Merge_Thr, on='Site' ,how='left')

HT_Site_Thr1['Index'] = HT_Site_Thr1['Site'].str.slice(start=0, stop=2)
HT_Site_Thr2 = pd.merge(HT_Site_Thr1,Prv_Name[['Index','Province_P']], on='Index' ,how='left') 

HT_Site_Thr3 = pd.merge(HT_Site_Thr2,Site_Address, on='Site' ,how='left')

In [34]:
HT_Site_Thr3['Outag'] = 'Nan'

In [35]:
HT_Site_Thr3 = HT_Site_Thr3[['Site','Province_P','Address','Daily Payload (GB)','Daily User Thr (Mbps)','Min Hourly User Thr (Mbps)','Min Hourly Sector User Thr sector(Mbps)','No. Carrir per Sector','Site BW','Outag','Lat','Long']]

In [36]:
HT_Site_Thr3.to_excel(r'D:\Shayan THR Report\Report File\{}\HighTraffic_Site_Total.xlsx'.format(Date))

# Low Thr Site

In [37]:
Traffic_Site = pd.read_excel(r'D:\Shayan THR Report\Report File\{}\Traffic_Site.xlsx'.format(Date),sheet_name='Sheet1')

In [38]:
Site_data = pd.merge(Merge_Thr,Traffic_Site[['Site','4G ppm']], on='Site' ,how='left')
Site_data['Index'] = Site_data['Site'].str.slice(start=0, stop=2)

In [39]:
Site_data_true1 = Site_data[Site_data['Daily User Thr (Mbps)']!=0]
Site_data_true2 = Site_data_true1[Site_data_true1['Min Hourly User Thr (Mbps)']!=0]
Site_data_true3 = Site_data_true2[Site_data_true2['Min Hourly Sector User Thr sector(Mbps)']!=0]
Site_data_true4 = Site_data_true3[Site_data_true3['Site BW']!=0]
Site_data_true5 = Site_data_true4[Site_data_true4['4G ppm']>9]

In [40]:
Low_Thr_Site = Site_data_true5.nsmallest(20,'Daily User Thr (Mbps)')

In [41]:
Low_Thr_Site = pd.merge(Low_Thr_Site,Prv_Name[['Index','Province_P']], on='Index' ,how='left')

In [42]:
Low_Thr_Site = pd.merge(Low_Thr_Site,Site_Address, on='Site' ,how='left')

In [43]:
Low_Thr_Site = Low_Thr_Site[['Site','Province_P','Address','Daily User Thr (Mbps)','Min Hourly User Thr (Mbps)','Min Hourly Sector User Thr sector(Mbps)','4G ppm','No. Carrir per Sector','Site BW','Lat','Long']]

In [44]:
Low_Thr_Site.to_excel(r'D:\Shayan THR Report\Report File\{}\Low_Thr_Site.xlsx'.format(Date))

# City Level

In [45]:
Site_City = pd.read_excel(r'D:\Shayan THR Report\Report File\Network Site DB.xlsx',sheet_name='DataBase')

In [46]:
Site_City1 = Site_City[['Site ID','City (Farsi)','Index']]
Site_City1 = Site_City1.rename({'Site ID':'Site'}, axis='columns')

In [125]:
#Merge_Thr = pd.read_excel(r'F:\Report\{}\Throughput.xlsx'.format(Date))

In [126]:
#Total_data_site_true = pd.read_excel(r'F:\Report\{}\Site_Report.xlsx'.format(Date),'Main')

In [47]:
Merge_1 = pd.merge(Merge_Thr,Site_City1,how='left',on=['Site'])

In [48]:
city_den = Merge_1.groupby(['Index','City (Farsi)'])['Connected_User'].agg(sum)

city_mult = pd.DataFrame()
city_mult['UDT'] = Merge_1['Daily User Thr (Mbps)'] * Merge_1['Connected_User']
city_mult['City (Farsi)'] = Merge_1['City (Farsi)']
city_mult['Index'] = Merge_1['Index']

city_mult_sum = city_mult.groupby(['Index','City (Farsi)'])['UDT'].agg(sum)

city_merged = pd.concat([ city_mult_sum , city_den ], axis = 1, sort=False)
city_merged['Daily User Thr (Mbps)'] = city_merged['UDT'] / (city_merged['Connected_User'] + (city_merged['Connected_User'] == 0))
city_merged.drop(['UDT'], axis=1, inplace = True)
city_merged_df = city_merged.reset_index()

In [49]:
site_data = pd.merge(Total_data_site_true,Site_City1,how='left',on=['Site'])

In [50]:
df_Agg_city = site_data.groupby(['City (Farsi)','Index_x','Status_name'],as_index=False)['Sector'].count()

In [51]:
df_Result_city = pd.pivot_table(df_Agg_city, values = 'Sector', index=['City (Farsi)','Index_x'], columns = 'Status_name').reset_index()

In [52]:
df_Result_city = df_Result_city.rename({'Index_x':'Index'}, axis='columns')

In [53]:
df_Result_city['3 (Mbps) < Thr < 5 (Mbps)'] = np.where(df_Result_city['3 (Mbps) < Thr < 5 (Mbps)'].isnull(),0,df_Result_city['3 (Mbps) < Thr < 5 (Mbps)'])
df_Result_city['5 (Mbps) < Thr < 10 (Mbps)'] = np.where(df_Result_city['5 (Mbps) < Thr < 10 (Mbps)'].isnull(),0,df_Result_city['5 (Mbps) < Thr < 10 (Mbps)'])
df_Result_city['Thr < 3 (Mbps)'] = np.where(df_Result_city['Thr < 3 (Mbps)'].isnull(),0,df_Result_city['Thr < 3 (Mbps)'])
df_Result_city['Thr > 10 (Mbps)'] = np.where(df_Result_city['Thr > 10 (Mbps)'].isnull(),0,df_Result_city['Thr > 10 (Mbps)'])

In [54]:
df_Result_city['# Site'] = df_Result_city['3 (Mbps) < Thr < 5 (Mbps)']+df_Result_city['5 (Mbps) < Thr < 10 (Mbps)']+df_Result_city['Thr < 3 (Mbps)']+df_Result_city['Thr > 10 (Mbps)']
df_Result_city['3 (Mbps) < %Thr < 5 (Mbps)'] = 100*df_Result_city['3 (Mbps) < Thr < 5 (Mbps)']/df_Result_city['# Site']
df_Result_city['5 (Mbps) < %Thr < 10 (Mbps)'] = 100*df_Result_city['5 (Mbps) < Thr < 10 (Mbps)']/df_Result_city['# Site']
df_Result_city['%Thr < 3 (Mbps)'] = 100*df_Result_city['Thr < 3 (Mbps)']/df_Result_city['# Site']
df_Result_city['%Thr > 10 (Mbps)'] = 100*df_Result_city['Thr > 10 (Mbps)']/df_Result_city['# Site']

In [55]:
Band = pd.merge(BW,Site_City1,how='left',on=['Site'])

In [56]:
BW_city = Band.groupby(['City (Farsi)','Index'],as_index=False)['BW_MHz'].mean()

In [57]:
city_details = pd.merge(city_merged_df,BW_city,how='left',on=['City (Farsi)','Index'])

In [58]:
city = pd.merge(df_Result_city,city_details,how='left',on=['City (Farsi)','Index'])

In [59]:
City_band = pd.read_excel(r'D:\Shayan THR Report\Report File\{}\City_Band.xlsx'.format(Date))

In [60]:
city = pd.merge(city,City_band,how='left',on=['City (Farsi)','Index'])

In [61]:
city.to_excel(r'D:\Shayan THR Report\Report File\{}\City_Low_Thr.xlsx'.format(Date))